<?php
/**
 * AuthResponse200Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  CaelumPhpClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Client Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-06-10T08:58:29Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CaelumPhpClient;

/**
 * AuthResponse200Test Class Doc Comment
 *
 * @category    Class
 * @description Successful response
 * @package     CaelumPhpClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthResponse200Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuthResponse200"
     */
    public function testAuthResponse200()
    {
    }

    /**
     * Test attribute "authToken"
     */
    public function testPropertyAuthToken()
    {
    }

    /**
     * Test attribute "refreshToken"
     */
    public function testPropertyRefreshToken()
    {
    }

    /**
     * Test attribute "statusCode"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }
}
