<?php
/**
 * DocumentListResponse200DataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CaelumPhpClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Client Public API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2022-06-10T08:58:29Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CaelumPhpClient;

/**
 * DocumentListResponse200DataTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentListResponse200Data
 * @package     CaelumPhpClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentListResponse200DataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentListResponse200Data"
     */
    public function testDocumentListResponse200Data()
    {
    }

    /**
     * Test attribute "totalDocs"
     */
    public function testPropertyTotalDocs()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }

    /**
     * Test attribute "totalPages"
     */
    public function testPropertyTotalPages()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "pagingCounter"
     */
    public function testPropertyPagingCounter()
    {
    }

    /**
     * Test attribute "hasPrevPage"
     */
    public function testPropertyHasPrevPage()
    {
    }

    /**
     * Test attribute "hasNextPage"
     */
    public function testPropertyHasNextPage()
    {
    }

    /**
     * Test attribute "docs"
     */
    public function testPropertyDocs()
    {
    }
}
